/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardIdRouteImport } from './routes/dashboard/$id'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as StatsIdIndexRouteImport } from './routes/stats/$id/index'
import { Route as DashboardPulsesIndexRouteImport } from './routes/dashboard/pulses/index'
import { Route as DashboardFlairsIndexRouteImport } from './routes/dashboard/flairs/index'
import { Route as StatsIdPulseIdRouteImport } from './routes/stats/$id/$pulseId'
import { Route as DashboardPulsesNewRouteImport } from './routes/dashboard/pulses/new'
import { Route as DashboardFlairsIdRouteImport } from './routes/dashboard/flairs/$id'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIdIndexRoute = StatsIdIndexRouteImport.update({
  id: '/stats/$id/',
  path: '/stats/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPulsesIndexRoute = DashboardPulsesIndexRouteImport.update({
  id: '/dashboard/pulses/',
  path: '/dashboard/pulses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFlairsIndexRoute = DashboardFlairsIndexRouteImport.update({
  id: '/dashboard/flairs/',
  path: '/dashboard/flairs/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIdPulseIdRoute = StatsIdPulseIdRouteImport.update({
  id: '/stats/$id/$pulseId',
  path: '/stats/$id/$pulseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPulsesNewRoute = DashboardPulsesNewRouteImport.update({
  id: '/dashboard/pulses/new',
  path: '/dashboard/pulses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFlairsIdRoute = DashboardFlairsIdRouteImport.update({
  id: '/dashboard/flairs/$id',
  path: '/dashboard/flairs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/flairs/$id': typeof DashboardFlairsIdRoute
  '/dashboard/pulses/new': typeof DashboardPulsesNewRoute
  '/stats/$id/$pulseId': typeof StatsIdPulseIdRoute
  '/dashboard/flairs/': typeof DashboardFlairsIndexRoute
  '/dashboard/pulses/': typeof DashboardPulsesIndexRoute
  '/stats/$id/': typeof StatsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/flairs/$id': typeof DashboardFlairsIdRoute
  '/dashboard/pulses/new': typeof DashboardPulsesNewRoute
  '/stats/$id/$pulseId': typeof StatsIdPulseIdRoute
  '/dashboard/flairs': typeof DashboardFlairsIndexRoute
  '/dashboard/pulses': typeof DashboardPulsesIndexRoute
  '/stats/$id': typeof StatsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/flairs/$id': typeof DashboardFlairsIdRoute
  '/dashboard/pulses/new': typeof DashboardPulsesNewRoute
  '/stats/$id/$pulseId': typeof StatsIdPulseIdRoute
  '/dashboard/flairs/': typeof DashboardFlairsIndexRoute
  '/dashboard/pulses/': typeof DashboardPulsesIndexRoute
  '/stats/$id/': typeof StatsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/callback'
    | '/dashboard/$id'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/flairs/$id'
    | '/dashboard/pulses/new'
    | '/stats/$id/$pulseId'
    | '/dashboard/flairs/'
    | '/dashboard/pulses/'
    | '/stats/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/callback'
    | '/dashboard/$id'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/auth'
    | '/dashboard'
    | '/dashboard/flairs/$id'
    | '/dashboard/pulses/new'
    | '/stats/$id/$pulseId'
    | '/dashboard/flairs'
    | '/dashboard/pulses'
    | '/stats/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/callback'
    | '/dashboard/$id'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/flairs/$id'
    | '/dashboard/pulses/new'
    | '/stats/$id/$pulseId'
    | '/dashboard/flairs/'
    | '/dashboard/pulses/'
    | '/stats/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardIdRoute: typeof DashboardIdRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFlairsIdRoute: typeof DashboardFlairsIdRoute
  DashboardPulsesNewRoute: typeof DashboardPulsesNewRoute
  StatsIdPulseIdRoute: typeof StatsIdPulseIdRoute
  DashboardFlairsIndexRoute: typeof DashboardFlairsIndexRoute
  DashboardPulsesIndexRoute: typeof DashboardPulsesIndexRoute
  StatsIdIndexRoute: typeof StatsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$id/': {
      id: '/stats/$id/'
      path: '/stats/$id'
      fullPath: '/stats/$id/'
      preLoaderRoute: typeof StatsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pulses/': {
      id: '/dashboard/pulses/'
      path: '/dashboard/pulses'
      fullPath: '/dashboard/pulses/'
      preLoaderRoute: typeof DashboardPulsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flairs/': {
      id: '/dashboard/flairs/'
      path: '/dashboard/flairs'
      fullPath: '/dashboard/flairs/'
      preLoaderRoute: typeof DashboardFlairsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/$id/$pulseId': {
      id: '/stats/$id/$pulseId'
      path: '/stats/$id/$pulseId'
      fullPath: '/stats/$id/$pulseId'
      preLoaderRoute: typeof StatsIdPulseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pulses/new': {
      id: '/dashboard/pulses/new'
      path: '/dashboard/pulses/new'
      fullPath: '/dashboard/pulses/new'
      preLoaderRoute: typeof DashboardPulsesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/flairs/$id': {
      id: '/dashboard/flairs/$id'
      path: '/dashboard/flairs/$id'
      fullPath: '/dashboard/flairs/$id'
      preLoaderRoute: typeof DashboardFlairsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardIdRoute: DashboardIdRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFlairsIdRoute: DashboardFlairsIdRoute,
  DashboardPulsesNewRoute: DashboardPulsesNewRoute,
  StatsIdPulseIdRoute: StatsIdPulseIdRoute,
  DashboardFlairsIndexRoute: DashboardFlairsIndexRoute,
  DashboardPulsesIndexRoute: DashboardPulsesIndexRoute,
  StatsIdIndexRoute: StatsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
